name: abricoz_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+5

environment:
  sdk: '>=3.3.4 <4.0.0'


  #Commands
  # flutter pub run build_runner build
  # flutter pub run build_runner watch
  # flutter pub run build_runner build --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1

  #UI
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.2.19
  flutter_screenutil: ^5.9.0
  figma_squircle: ^0.5.3
  mask_text_input_formatter: ^2.3.0
  pin_code_fields: ^8.0.1
  infinite_scroll_pagination: ^4.0.0
  flutter_svg: ^2.0.5
  cached_network_image: ^3.3.1
  expandable: ^5.0.1
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  animated_custom_dropdown: ^3.0.0
  package_info_plus: ^8.0.1
  in_app_review: ^2.0.9
  sliding_up_panel: ^2.0.0+1
  badges: ^3.1.2
  flutter_cache_manager: ^3.4.1
  floating_menu_panel: ^0.0.2

  #map
  yandex_mapkit: ^4.1.0
  geolocator: ^13.0.1


  #chache
  get_storage: ^2.0.3
  shared_preferences: ^2.0.18
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #file
  file_picker: ^8.0.3
  mime: ^1.0.4
  image_picker: ^1.1.2


  #others
  dartz: ^0.10.1
  equatable: ^2.0.3
  intl: ^0.19.0
  url_launcher: ^6.1.10
  permission_handler: ^11.3.1
  auto_route: ^8.1.3
  upgrader: ^10.3.0

  # State management
  flutter_bloc: ^8.1.2

  # API
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  dio: ^5.0.2
  http: ^1.2.1
  connectivity_plus: ^6.0.4
  device_info_plus: ^10.1.2
  app_links: ^6.3.2

  #firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.4
  firebase_crashlytics: ^4.1.2
  firebase_analytics: ^11.3.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1


  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  ios_content_mode: center
  remove_alpha_ios: true
  android_content_mode: center
  image_path: "assets/images/logo/logo.png"
  adaptive_icon_foreground: "assets/images/logo/logo_fore.png"
  adaptive_icon_background: "assets/images/logo/logo_back.png"

flutter_native_splash:

  color: "#FE5000"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash12.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/navigation/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter-Light.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/Inter-Thin.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: ru # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: assets/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/src/common/utils/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false
