// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDVumwB9NOw4sQzOgvjw3Ub62T4Z4krJ8',
    appId: '1:775143759922:web:6b17c1d525e4af08285c2b',
    messagingSenderId: '775143759922',
    projectId: 'abricoz-94dfc',
    authDomain: 'abricoz-94dfc.firebaseapp.com',
    storageBucket: 'abricoz-94dfc.appspot.com',
    measurementId: 'G-M2VRXBDKKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAILw7MVRWD4_I534vZkFPwhwH3gdWWrfY',
    appId: '1:775143759922:android:39bb51ded158afa7285c2b',
    messagingSenderId: '775143759922',
    projectId: 'abricoz-94dfc',
    storageBucket: 'abricoz-94dfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4-SIhYhUGGX8cvu8Ep8XHLCmwXysN9DA',
    appId: '1:775143759922:ios:0af29c2652e310d7285c2b',
    messagingSenderId: '775143759922',
    projectId: 'abricoz-94dfc',
    storageBucket: 'abricoz-94dfc.appspot.com',
    iosBundleId: 'com.abricoz.app',
  );
}
